banknotes =  int(input())
print(banknotes)
print("{} nota(s) de R$ 100,00".format(int(banknotes/100)))
remaining = (banknotes%100)
print("{} nota(s) de R$ 50,00".format(int(remaining/50)))
remaining = (remaining%50)
print("{} nota(s) de R$ 20,00".format(int(remaining/20)))
remaining = (remaining%20)
print("{} nota(s) de R$ 10,00".format(int(remaining/10)))
remaining = (remaining%10)
print("{} nota(s) de R$ 5,00".format(int(remaining/5)))
remaining = (remaining%5)
print("{} nota(s) de R$ 2,00".format(int(remaining/2)))
remaining = (remaining%2)
print("{} nota(s) de R$ 1,00".format(int(remaining/1)))